name: First Workflow
on: workflow_dispatch    #event can be trigged manually from e.g.CLI
jobs:
  first-job:
    runs-on: windows-latest
    steps:
      - name: Print greeting
        run: |    #visto che here stai usando shell commands, con | permetti testo multilinea!s
          echo "hello world"
          echo "second rendered text"
      - name: Print goodbye
        run: echo "done - bye!"
